// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDN2xYZ5vO4ot-0k3A7371LNchQEM9mKNg',
    appId: '1:956781565906:web:c4a82025ad87a43507da0b',
    messagingSenderId: '956781565906',
    projectId: 'ecommerce-78aab',
    authDomain: 'ecommerce-78aab.firebaseapp.com',
    storageBucket: 'ecommerce-78aab.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZQi9mA_F5eGJfvG84UmcftAQ29unysx8',
    appId: '1:956781565906:android:ecf7d72f2887c69107da0b',
    messagingSenderId: '956781565906',
    projectId: 'ecommerce-78aab',
    storageBucket: 'ecommerce-78aab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsCw9jkY2wV3AUq4N3LhZE2hdssOSFlqs',
    appId: '1:956781565906:ios:098c55c8c21e7cbb07da0b',
    messagingSenderId: '956781565906',
    projectId: 'ecommerce-78aab',
    storageBucket: 'ecommerce-78aab.appspot.com',
    iosBundleId: 'com.example.firstProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsCw9jkY2wV3AUq4N3LhZE2hdssOSFlqs',
    appId: '1:956781565906:ios:098c55c8c21e7cbb07da0b',
    messagingSenderId: '956781565906',
    projectId: 'ecommerce-78aab',
    storageBucket: 'ecommerce-78aab.appspot.com',
    iosBundleId: 'com.example.firstProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDN2xYZ5vO4ot-0k3A7371LNchQEM9mKNg',
    appId: '1:956781565906:web:c9364111d33185ca07da0b',
    messagingSenderId: '956781565906',
    projectId: 'ecommerce-78aab',
    authDomain: 'ecommerce-78aab.firebaseapp.com',
    storageBucket: 'ecommerce-78aab.appspot.com',
  );
}
